:backends:
  - json

:logging:
  console

:hierarchy:
  - ../../config/%{::environment}/%{::fqdn}
  - %{::environment}/%{::fqdn}
  - ../../config/%{::environment}/%{::role}
  - %{::environment}/%{::role}
  - ../../config/%{::environment}/common
  - %{::environment}/common
  - ../../config/%{::fqdn}
  - %{::fqdn}
  - ../../config/%{::role}
  - %{::role}
  - ../../config/common
  - common
  - deploy
  - ../../config/project

:json:
  :datadir: "env/config"