:backends:
  - json

:logging:
  console

:hierarchy:
  - ../../config/%{::environment}/%{::certname}
  - %{::environment}/%{::certname}
  - ../../config/%{::environment}/%{::role}
  - %{::environment}/%{::role}
  - ../../config/%{::environment}/common
  - %{::environment}/common
  - ../../config/%{::certname}
  - %{::certname}
  - ../../config/%{::role}
  - %{::role}
  - ../../config/common
  - common
  - ../../config/project

:json:
  :datadir: "env/config"