:backends:
  - json

:logging:
  console

:hierarchy:
  - ../../%{::environment}/%{::certname}
  - %{::environment}/%{::certname}
  - ../../%{::environment}/%{::role}
  - %{::environment}/%{::role}
  - ../../%{::environment}/common
  - %{::environment}/common
  - ../../%{::certname}
  - %{::certname}
  - ../../%{::role}
  - %{::role}
  - ../../%{::common}
  - common

:json:
  :datadir: "env/config"