--- 
? !ruby/symbol backends
: 
  - json
? !ruby/symbol hierarchy
: 
  - "../../config/%{::environment}/%{::fqdn}"
  - "../../config/%{::environment}/%{::hostname}"
  - "../../config/%{::fqdn}"
  - "../../config/%{::hostname}"
  - "%{::environment}/%{::fqdn}"
  - "%{::environment}/%{::hostname}"
  - "%{::fqdn}"
  - "%{::hostname}"
  - "../../config/%{::environment}/%{::role}"
  - "%{::environment}/%{::role}"
  - "../../config/%{::environment}/common"
  - "%{::environment}/common"
  - "../../config/%{::role}"
  - "%{::role}"
  - ../../config/common
  - common
  - ../../config/project
? !ruby/symbol json
: 
  ? !ruby/symbol datadir
  : env/config
? !ruby/symbol logging
: console
