:backends:
  - json

:logging:
  console

:hierarchy:
  - %{::environment}/%{::certname}
  - %{::environment}/%{::location}
  - %{::environment}/%{::role}
  - %{::environment}/common
  - %{::certname}
  - %{::location}
  - %{::role}
  - project
  - common

:json:
  :datadir: "env/config"